services:
  - type: web
    name: fitpulse-health-anomaly-detection
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
